/'
 ' Licensed to the Apache Software Foundation (ASF) under one
 ' or more contributor license agreements.  See the NOTICE file
 ' distributed with this work for additional information
 ' regarding copyright ownership.  The ASF licenses this file
 ' to you under the Apache License, Version 2.0 (the
 ' "License"); you may not use this file except in compliance
 ' with the License.  You may obtain a copy of the License at
 '
 '    http://www.apache.org/licenses/LICENSE-2.0
 '
 ' Unless required by applicable law or agreed to in writing, software
 ' distributed under the License is distributed on an "AS IS" BASIS,
 ' WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 ' See the License for the specific language governing permissions and
 ' limitations under the License.
 '/

@startuml
'https://plantuml.com/class-diagram

package Client {
    class StreamGraph {
        streamNodes : Map<Integer, StreamNode>
        sources: Set<Integer>
        sinks: Set<Integer>
        virtualSideOutputNodes: Map<Integer, Tuple2<Integer, OutputTag>>
        __
        getJobName() : String
        getJobType() : JobType
        ..
        addOperator(..) : void
        addSource(..) : void
        addSink(..) : void
    }
    note left of StreamGraph: Unserialized representation of the job.

    class StreamNode {
        id : int
        transformationUUID : String
        userHash : String
        ..
        minResources : ResourceSpec
        preferredResources ResourceSpec
        ..
        slotSharingGroup : String
        coLocationGroup : String
        ..
        operatorFactory : StreamOperatorFactory
        typeSerializerIn : TypeSerializer<?>
        typeSerializerOut : TypeSerializer<?>
        inEdges : List<StreamEdge>
        outEdge : List<StreamEdge>
        inputFormat : InputFormat
        outputFormat : OutputFormat
    }

    class StreamEdge {
        edgeId : String
        sourceId : int
        sourceOperatorName : String
        targetId : int
        targetOperatorName : String
        outputTag : OutputTag
        outputPartitioner : StreamPartitioner
        exchangeMode : StreamExchangeMode
        intermediateDatasetIdToProduce : IntermediateDataSetID
    }

    class JobGraph {
        getJobID() : JobID
        getName() : String
        ..
        getJobType() : JobType
        getMaximumParallelism() : int
        getJobConfiguration() : Configuration
        getCheckpointSettings() : JobCheckpointingSettings
        getInitialClientHeartbeatTimeout() : long
        getSavepointRestoreSettings() : SavepointRestoreSettings
        getSerializedExecutionConfig() : SerializedValue<ExecutionConfig>
        isDynamic() : boolean
        isCheckpointingEnabled() : boolean
        isApproximateLocalRecoveryEnabled() : boolean
        ..
        getVertices() : Iterable<JobVertex>
        getVerticesAsArray() : JobVertex[]
        findVertexByID(JobVertexID) : JobVertex
        getNumberOfVertices() : int
        ..
        getSlotSharingGroups() : Set<SlotSharingGroup>
        getCoLocationGroups() : Set<CoLocationGroup>
        getJobStatusHooks() : List<JobStatusHook>
        ..
        getUserArtifacts() : Map<String, DistributedCacheEntry>
        getUserJarBlobKeys() : List<PermanentBlobKey>
        getUserJars() : List<Path>
        hasUsercodeJarFiles() : boolean
    }
    note left of JobGraph: Serializable representation of the job.

    class JobVertex {
        getID() : JobVertexID
        getName() : String
        getParallelism() : int
        getMaxParallelism() : int
        getSlotSharingGroup() : SlotSharingGroup
        getInvokableClass(ClassLoader) : Class
        getOperatorIDs() : List<OperatorIDPair>
        [...] ()
    }
    note left of JobVertex: Serializable representation of a JobGraph's task.
}

package JobManager {
    interface AccessExecutionGraph {
        getJobID() : JobID
        getJobName() : String
        getJsonPlan() : String
        getArchivedExecutionConfig() : ArchivedExecutionConfig
        ..
        getCheckpointCoordinatorConfig() : CheckpointCoordinatorConfig
        getStateBackendName() : String
        getCheckpointStorageName() : String
        getChangelogStorageName() : String
        ..
        getJobState() : JobStatus
        getStatusTimestamp(JobStatus) : long
        getFailureInfo() : ErrorInfo
        ..
        getJobVertex(JobVertexID) : AccessExecutionJobVertex
        getAllVertices() : Map<JobVertexID, AccessExecutionJobVertex>
        getVerticesTopologically() : Iterable<AccessExecutionJobVertex>
        getAllExecutionVertices() : Iterable<AccessExecutionVertex>
        ..
        getCheckpointStatsSnapshot() : CheckpointStatsSnapshot
        ..
        getAccumulatorResultsStringified() : StringifiedAccumulatorResult[]
        getAccumulatorsSerialized() : Map<String, SerializedObject>
    }
    note right of AccessExecutionGraph: Representation of a JobGraph while executing the job.

    interface ExecutionGraph {

    }

    interface AccessExecutionJobVertex {
        getJobVertexId() : JobVertexID
        getName() : String
        ..
        getParallelism() : int
        getMaxParallelism() : int
        getResourceProfile() : ResourceProfile
        ..
        getAggregatedState() : ExecutionState
        ..
        getTaskVertices() : AccessExecutionVertex[]
        ..
        getAggregatedUserAccumulatorsStringified() : StringifiedAccumulatorResult[]
    }
    note right of AccessExecutionJobVertex: Representation of a JobVertex while executing the job.

    interface AccessExecutionVertex {
        getTaskNameWithSubtaskIndex() : String
        getParallelSubtaskIndex() : int
        ..
        getExecutionState() : ExecutionState
        getStateTimestamp(ExecutionState) : long
        getFailureInfo() : ErrorInfo
        getExecutionHistory() : ExecutionHistory
        ..
        getCurrentExecutionAttempt() : AccessExecution
        ..
        getCurrentAssignedResourceLocation() : TaskManagerLocation
    }
    note right of AccessExecutionVertex: A parallel instance of the AccessExecutionJobVertex (i.e. a JobVertex of parallelism n results in n AccessExecutionVertex instance for the corresponding AccessExecutionJobVertex)

    interface AccessExecution {
        getAttemptId() : ExecutionAttemptID
        getParallelSubtaskIndex() : int
        getAttemptNumber() : int
        ..
        getState() : ExecutionState
        getStateTimestamps() : long[]
        getStateEndTimestamps() : long[]
        getStateTimestamp(ExecutionState) : long
        getStateEndTimestamp(ExecutionState) : long
        getFailureInfo() : ErrorInfo
        ..
        getAssignedResourceLocation() : TaskManagerLocation
        ..
        getUserAccumulatorsStringified() : StringifiedAccumulatorResult[]
        getIOMetrics() : IOMetrics
    }
    note right of AccessExecution: The actual execution abstraction of AccessExecutionVertex (multiple attempts can be made to execute AccessExecutionVertex)

    class Execution implements AccessExecution {
    }
}

package TaskManager {
    class Task {
    }

    interface TaskInvokable {
    }

    class StreamTask implements TaskInvokable

    class AbstractInvokable implements TaskInvokable

    class BatchTask implements AbstractInvokable

    note right of Task: TaskExecutor representation of an Execution instance
}

StreamGraph ...> JobGraph : compiles into
StreamGraph ..> StreamNode : contains
StreamGraph ..> StreamEdge : contains
StreamEdge ..> StreamNode :: connects
JobGraph ..> JobVertex : contains
ExecutionGraph --|> AccessExecutionGraph
AccessExecutionGraph ..> AccessExecutionJobVertex : contains
AccessExecutionJobVertex ..> AccessExecutionVertex : contains
AccessExecutionVertex ..> AccessExecution : contains
Execution ..> Task : deploys
Task ..> TaskInvokable : runs

JobGraph ..> AccessExecutionGraph : represents
JobVertex ..> AccessExecutionJobVertex : represents

@enduml
