@startuml
'https://plantuml.com/class-diagram

title Proposed refactoring of the multi-component Leader Election that was introduced in Apache Flink 1.15+ (FLINK-26522)

interface LeaderContender {
    void grantLeadership(leaderSessionID)
    void revokeLeadership()
    String getLeaderContenderLabel()
}
hide LeaderContender fields
note right: <b>LeaderContender.getLeaderContenderLabel()</b>\n is used to access the componentId

interface LeaderElectionDriver {
    void writeLeaderInformation(LeaderInformation)
    boolean hasLeadership()
    void close()
}
hide LeaderElectionDriver fields

interface LeaderElectionEventHandler {
    void onGrantLeadership(newLeaderSessionId)
    void onRevokeLeadership()
    void onLeaderInformationChange(leaderInformation)
}
hide LeaderElectionEventHandler fields

interface LeaderElectionService {
    void start()
    CompletableFuture<Void> closeAsync()
    void register(LeaderContender)
    void deregister(LeaderContender)
    void confirmLeadership(leaderSessionID, leaderAddress)
    boolean hasLeadership(leaderSessionId)
}
hide LeaderElectionService fields
note left of LeaderElectionService
- <b>register</b>/<b>deregister</b> introduced to add/remove contenders
- <b>start</b>/<b>closeAsync</b> used for managing the leader election driver lifecycle
end note

class DefaultLeaderElectionService {
    leaderElectionDriver: LeaderElectionDriver
    leaderContenders: Collection<LeaderContender>
}
hide DefaultLeaderElectionService methods

class ZooKeeperLeaderElectionDriver implements LeaderElectionDriver
hide ZooKeeperLeaderElectionDriver members

class KubernetesLeaderElectionDriver implements LeaderElectionDriver
hide KubernetesLeaderElectionDriver members

class DefaultLeaderElectionService implements LeaderElectionService, LeaderElectionEventHandler

LeaderElectionDriver ---> LeaderElectionEventHandler : uses
DefaultLeaderElectionService --> LeaderElectionDriver : uses
DefaultLeaderElectionService --> LeaderContender : uses
LeaderContender --> LeaderElectionService : uses

@enduml