name: Generate SVGs
on:
  push:
    branches:
      - main
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Generate SVGs
        id: plantuml
        uses: grassedge/generate-plantuml-action@master
        with:
          path: diagrams
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
